name: Build App for the First Time

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Install Capacitor packages including Android
      - name: Install Capacitor dependencies
        run: npm install @capacitor/core @capacitor/cli @capacitor/android

      # Step 5: Initialize Capacitor (this creates or updates capacitor.config.json with webDir as "www")
      - name: Initialize Capacitor
        run: npx cap init "CommentarySync" "com.example.commentarysync" --web-dir www

      # Step 6: Add Android platform
      - name: Add Android platform
        run: npx cap add android

      # Step 7: Build the web project (assumed to output to "dist")
      - name: Build web project
        run: npm run build

      # Step 8: Rename the build output from "dist" to "www" (so that Capacitor finds the web assets)
      - name: Rename build output to www
        run: |
          if [ -d "dist" ]; then
            rm -rf www
            mv dist www
          else
            echo "dist directory not found!"
            exit 1
          fi

      # Step 9: Copy web assets into the native Android project
      - name: Copy web assets
        run: npx cap copy android

      # Step 10: Build the Android APK
      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleDebug

      # Step 11: Upload the APK as an artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: commentarysync-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
