name: Build App for the First Time

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Install Capacitor packages including the Android package
      - name: Install Capacitor dependencies
        run: npm install @capacitor/core @capacitor/cli @capacitor/android

      # Step 5: Initialize Capacitor
      - name: Initialize Capacitor
        run: npx cap init "CommentarySync" "com.example.commentarysync" --web-dir www

      # Step 6: Add Android platform
      - name: Add Android platform
        run: npx cap add android

      # Step 7: Build the web project (adjust if your build command is different)
      - name: Build web project
        run: npm run build

      # Step 8: Copy web assets to the native Android project
      - name: Copy web assets
        run: npx cap copy android

      # Step 9: Build the Android APK
      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleDebug

      # Step 10: Upload the APK as an artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: commentarysync-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
