name: Build App for the First Time

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4  # Use the latest checkout action

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4  # Latest version of Node.js setup
        with:
          node-version: 18  # Use Node.js 18 or the version you need

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Install Capacitor dependencies
      - name: Install Capacitor dependencies
        run: |
          npm install @capacitor/core @capacitor/cli

      # Step 5: Initialize Capacitor (if not already initialized)
      - name: Initialize Capacitor
        run: |
          npx cap init "CommentarySync" "com.example.commentarysync" --web-dir www

      # Step 6: Add Android platform
      - name: Add Android platform
        run: |
          npx cap add android

      # Step 7: Build the project
      - name: Build project
        run: npm run build  # Or your project's build command (e.g., "npm run build")

      # Step 8: Build Android APK
      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleDebug  # Builds the APK

      # Step 9: Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4  # Latest version of the upload-artifact action
        with:
          name: app-build
          path: dist/  # Adjust based on where your build output goes (e.g., dist/ or android/app/build)
