name: First-Time Build App

on:
  push:
    branches:
      - main

jobs:
  first-time-build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository and set up Node.js
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 2. Install project and Capacitor dependencies
      - name: Install dependencies
        run: npm install

      - name: Install Capacitor dependencies
        run: npm install @capacitor/core @capacitor/cli @capacitor/android

      # 3. Initialize Capacitor (creates/updates capacitor.config.json with webDir as "www")
      - name: Initialize Capacitor
        run: npx cap init "CommentarySync" "com.example.commentarysync" --web-dir www

      # 4. Add Android platform (creates the native Android project structure)
      - name: Add Android platform
        run: npx cap add android

      # 5. Build the web project (assumed to output to "dist")
      - name: Build web project
        run: npm run build

      # 6. Rename the build output from "dist" to "www" so that Capacitor finds the web assets
      - name: Rename build output to www
        run: |
          if [ -d "dist" ]; then
            rm -rf www
            mv dist www
          else
            echo "dist directory not found!"
            exit 1
          fi

      # 7. Copy web assets into the native Android project
      - name: Copy web assets to Android
        run: npx cap copy android

      # 8. Update android/settings.gradle to include required Capacitor modules
      - name: Update android/settings.gradle
        run: |
          cat > android/settings.gradle << 'EOF'
          include ':app'
          include ':capacitor-android'
          include ':capacitor-cordova-android-plugins'
          project(':capacitor-android').projectDir = new File(rootProject.projectDir, '../node_modules/@capacitor/android/capacitor')
          project(':capacitor-cordova-android-plugins').projectDir = new File(rootProject.projectDir, '../node_modules/@capacitor/cli/capacitor-cordova-android-plugins')
          EOF

      # 9. Build the Android APK using Gradle
      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleDebug

      # 10. Upload the generated APK as an artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: commentarysync-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
